version: '3.1'
services:
  magento-mysql-server:
    image: mysql:8.0.29
    container_name: magento-mysql-server
    ports:
      - "33066:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=magento1234
      - MYSQL_DATABASE=magento
    mem_reservation: "2096M"
    volumes:
      - "./database:/var/lib/mysql"
  magento-elasticsearch-server:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: magento-elasticsearch-server
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      - discovery.type=single-node
